### ISSUE TITLE
Project Panel not resizing properly

### ISSUE THREAD

**Issue by efrantar-tgm** [TGM-HIT/eqep-website#4]
When the `log-panel` is pulled up over the `project-panel`, the `project-panel` pops up so that it's still visible (that's good). But when the `log-panel` is pulled down again, the `project-panel` stays where it is ...

![tmp](https://cloud.githubusercontent.com/assets/2834424/5595669/8be75f4a-9279-11e4-84d7-673c378ea15b.png)

**Comment by aaly-tgm** [comment]
website doesn't exist anymore
