### ISSUE TITLE
Javascript Injection

### ISSUE THREAD

**Issue by gye-tgm** [TGM-HIT/eqep-website#8]
If I create a file named `a" onclick="alert('Hallo');"></li>.kml` then it will cause a Java script injection.

![screen shot 2015-03-03 at 14 15 15](https://cloud.githubusercontent.com/assets/2834414/6463139/cf42460a-c1af-11e4-9248-8736bc7ed192.png)

**Comment by aaly-tgm** [comment]
This problem only occurs at MacOSX machines. 
Only MacOSX operating systems are allowed to create filenames with a forwardslash "/" for example.
The server will be running on a linux operating system.
